language: node_js
node_js: stable

# safelist
branches:
  only:
  - master

cache:
  yarn: true
  directories:
    - $TRAVIS_BUILD_DIR/source/rodemsdev.ui/node_modules

script: 
  - $TRAVIS_BUILD_DIR/source/rodemsdev.ui yarn test
  - $TRAVIS_BUILD_DIR/source/rodemsdev.ui yarn deploy