language: node_js
node_js: stable

# safelist
branches:
  only:
  - master

cache:
  yarn: true
  directories:
    - $TRAVIS_BUILD_DIR/rodemsdev/source/rodemsdev.ui/node_modules

script: 
  - $TRAVIS_BUILD_DIR/rodemsdev/build.sh
