# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev CI

on:
  push:
    branches: [ feature/*, feature-fix/*, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci-build:
    name: CI Build
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn install
      working-directory: ./source/ui
      run: yarn

    - name: yarn test:ci
      working-directory: ./source/ui
      run: yarn test:ci

    - name: yarn build
      working-directory: ./source/ui
      run: yarn build --if-present
