# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-Build

on:
  push:
    branches:
      - master
  pull_request:
  page_build:
  release:
    types:
      - created

jobs:
  cache-or-install:
    name: CACHE OR INSTALL
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v2
      name: cache node modules
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: yarn install
      working-directory: ./source/ui
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

  test:
    name: TEST
    runs-on: ubuntu-latest
    needs: [cache-or-install]
        
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v2
      name: cache node modules
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: yarn test:ci
      working-directory: ./source/ui
      run: yarn test:ci

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v1
      if: ${{ always() }}
      with:
        report_paths: '**/junit.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./source/ui/reports/coverage/lcov.info
        flags: tests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: true

  build: 
    name: BUILD
    runs-on: ubuntu-latest
    needs: [cache-or-install, test]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v2
      name: cache node modules
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: yarn build
      working-directory: ./source/ui
      run: yarn build --if-present

  deploy: 
    name: DEPLOY
    runs-on: ubuntu-latest
    needs: [cache-or-install, test, build]
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v2
      name: Cached Node Modules
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./source/ui/build
        cname: rodems.dev
        keep_files: true
