# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev CI

on:
  push:
    branches: [ feature/*, feature-fix/*, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci-build:
    name: CI Build
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: yarn install
      working-directory: ./source/ui
      run: yarn install --frozen-lockfile

    - name: yarn test:ci
      working-directory: ./source/ui
      run: yarn test:ci

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v1
      if: ${{ always() }}
      with:
        report_paths: '**/junut.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./source/ui/reports/coverage/clover.xml
        flags: tests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: true

    - name: yarn build
      working-directory: ./source/ui
      run: yarn build --if-present
